
#Configuarartion
spring:
application:
    name: Bookservice
server:
   port: 8090

#DEBUGGING
logging:
   level:
       org:
          springframework:
                    web: DEBUG

#Data
apipothi:
bookdescription:
               Demo project to read from Application file in spring Boot
bookid: 1,2,3,4,5,6,7,8,9
bookprice:
   100,200,300,400,500,600,700,800,900
booksname:
   JAVA,Microservices,Webservices,Python,Go,Spring,Springboot,JSF,Struts
bookswitchprice:
                 '{
                  JAVA: "900",
                  Microservices:"901",
                  ,Python:"902"
                  }'
booknotabalable:
   true


